"""initial_schema

Revision ID: 563c6fc1470f
Revises: 
Create Date: 2026-09-16 10:25:33.918204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563c6fc1470f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False, comment='Canonical course identifier, e.g. CS101'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('credit_units', sa.Integer(), nullable=False),
    sa.CheckConstraint('credit_units > 0', name='ck_courses_credit_units_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matric_number', sa.String(length=50), nullable=False, comment='Unique institutional student identifier, e.g. CSC/2020/001'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('enrollment_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_matric_number'), 'students', ['matric_number'], unique=True)
    op.create_table('academic_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False, comment='E.g. "First Semester 2024/2025" or "Fall 2025"'),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', name='gradeenum'), nullable=False),
    sa.Column('grade_point', sa.Float(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_academic_records_score_bounds'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', 'semester', name='uq_academic_records_student_course_semester')
    )
    op.create_index('ix_academic_records_student_semester', 'academic_records', ['student_id', 'semester'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_academic_records_student_semester', table_name='academic_records')
    op.drop_table('academic_records')
    op.drop_index(op.f('ix_students_matric_number'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
